---
parser: babel-eslint
extends:
- standard
- standard-react
env:
  serviceworker: true
  browser: true
  node: true
rules:
  react/react-in-jsx-scope:
  - 0
  react/prop-types:
  - warn
  - skipUndeclared: true
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  - 90
  - ignoreStrings: true
  - ignoreTemplateLiterals: true
  max-lines:
  - warn
  - 300
